name: Build and Push docker image

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: harryagstian/test-server:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build --tag ${{ env.IMAGE_TAG }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: harryagstian
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push ${{ env.IMAGE_TAG }}
