name: Main branch pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yaml
    secrets:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
